version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka

  example-receive:
    build:
      context: ./example-receive
    container_name: example-receive
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092

  example-send:
    build:
      context: ./example-send
    container_name: example-send
    depends_on:
      - kafka
      - example-receive
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092

  supervisor:
    image: alpine
    container_name: supervisor
    depends_on:
      - example-send
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    working_dir: /app
    command: sh supervisor.sh

volumes:
  zookeeper_data:
  kafka_data:
