version: '3.8'

services:
  kafka:
    extends:
      file: docker-compose.kafka.yaml
      service: kafka

  example-receive:
    build:
      context: ./example-receive
    container_name: example-receive
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092

  example-send:
    build:
      context: ./example-send
    container_name: example-send
    depends_on:
      - kafka
      - example-receive
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092

volumes:
  kafka_data:
