name: Test the Echosystem

on:
  push:
    branches:
      - main

jobs:
  test-echosystem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run docker compose
        run: |
          docker compose up -d
      - name: Shutdown after 3 minutes
        run: |
          sleep 180
          docker compose logs > logs.txt
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fluid-builder-compose-logs
          path: logs.txt
      - name: Stop and remove containers
        run: |
          docker compose down -v