name: Test the Echosystem

on:
  push:
    branches:
      - main

jobs:
  test-echosystem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for System to Run
        run: sleep 180

      - name: Capture Docker Logs
        run: docker compose logs > logs.txt

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fluid-builder-compose-logs
          path: logs.txt

      - name: Count Messages Received (with Status)
        run: |
          echo "Analyzing message counts from logs..."
          awk '
          /example-receive[[:space:]]*\|[[:space:]]*1-Received:/ {c1++}
          /example-receive[[:space:]]*\|[[:space:]]*2-Received:/ {c2++}
          /example-receive[[:space:]]*\|[[:space:]]*3-Received:/ {c3++}
          END {
            printf "%-30s | %-5s | %-6s\n", "Pattern", "Count", "Status"
            printf "%-30s | %-5d | %-6s\n", "example-receive | 1-Received:", c1+0, (c1 == 1000 ? "✅" : "❌")
            printf "%-30s | %-5d | %-6s\n", "example-receive | 2-Received:", c2+0, (c2 == 1000 ? "✅" : "❌")
            printf "%-30s | %-5d | %-6s\n", "example-receive | 3-Received:", c3+0, (c3 == 1000 ? "✅" : "❌")
          }
          ' logs.txt

      - name: Cleanup - Stop and Remove Containers
        run: docker compose down -v
